# Generated by Django 4.1.1 on 2022-10-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, null=True)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, null=True, unique=True)),
                ('nombre', models.CharField(max_length=25, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('region', models.CharField(max_length=25, null=True)),
                ('correo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_compra', models.IntegerField()),
                ('factura', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrega', models.DateTimeField(auto_now_add=True)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, null=True)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuento', models.CharField(max_length=4)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPedido', models.CharField(max_length=10, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=40, null=True)),
                ('pais', models.CharField(max_length=10, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumOrden', models.CharField(max_length=20, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.cliente')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.forma_envio')),
                ('numPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=25, null=True, unique=True)),
                ('nombre', models.CharField(max_length=25, null=True)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('imagen', models.ImageField(blank=True, default='', upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.estado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.marca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.producto'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_existencia', models.IntegerField()),
                ('unidades_pedidos', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('fechaHora', models.DateTimeField(auto_now_add=True, null=True)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.producto')),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.detalle_compra')),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.detalle_venta')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.movimiento')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.producto'),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.venta'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='nombre_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.producto'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='nro_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPI.proveedor'),
        ),
    ]
